name: lf-sample-repository-api-nodejs-CI

on:
  push:
    branches: [ '\d+.x' ]
  pull_request:
    branches: [ '\d+.x' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: Npm i
        run: npm i

      - name: Npm run lint
        run: npm run lint
      
      - name: Npm run build
        run: npm run build
        
      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./README.md
            ./LICENSE
