name: lf-sample-repository-api-nodejs-CI

on:
  push:
    branches: [v][123456789]
  pull_request:
    branches: [v][123456789]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '18'

      - name: Npm tool install
        run: npm install -g npm@8

      - name: Npm i
        run: npm i

      - name: Npm run lint
        run: npm run lint
      
      - name: Npm run build
        run: npm run build
      
      - name: Npm run start
        env:
            ACCESS_KEY: ${{ secrets.DEV_CA_PUBLIC_USE_INTEGRATION_TEST_ACCESS_KEY }}
            SERVICE_PRINCIPAL_KEY:  ${{ secrets.DEV_CA_PUBLIC_USE_TESTOAUTHSERVICEPRINCIPAL_SERVICE_PRINCIPAL_KEY }}
            REPOSITORY_ID:  ${{ secrets.DEV_CA_PUBLIC_USE_REPOSITORY_ID_1 }}
            AUTHORIZATION_TYPE: ${{ secrets.AUTHORIZATION_TYPE }}
        run: npm run start
